### ISSUE TITLE
Missing ipv6 routing...?

### ISSUE THREAD

**Issue by marcussacana** [hillz2/openwrt_cloudflare_warp#2]
I'm not a expert into this, but by ipv4 only I wasn't able to pass in the clouflare test with ipv6 enabled.
![image](https://github.com/user-attachments/assets/01fc08b5-651d-4d4a-9085-b213a565007d)
As you can see only ipv4 is ussing WRAP

**Comment by marcussacana** [comment]
I was able to setup by creating a ipv6 NAT network
I think the key points are
- Set the wireguard as the DHCPv6 designed master
- Change LAN to act as DHCPv6 server and not retransmissor
- Enable the IPv6 Masquerading at wireguard zone

Some screenshots of my settings if anyone wants:
![image](https://github.com/user-attachments/assets/598b6c1f-3fe9-4b5a-85b7-f8fba5d3b1ce)
![image](https://github.com/user-attachments/assets/40513626-c3cf-4555-b827-b3edb5a4516b)
![image](https://github.com/user-attachments/assets/83a59ada-4a61-42ed-ae1c-61d9aa3335a1)
![image](https://github.com/user-attachments/assets/ec7076c9-d5b0-496f-9e59-a7e823f642c6)
![image](https://github.com/user-attachments/assets/51b9c779-c502-4cdf-9b2a-3fa5ea23c0c6)
![image](https://github.com/user-attachments/assets/2eec2b68-055e-4f02-a5de-a422f61914e8)

A part of my /etc/config/network file:
```python
config interface 'wan6'
	option device 'wan'
	option proto 'dhcpv6'
	option reqaddress 'none'
	option reqprefix 'no'
	option metric '1025'

config interface 'wg0'
	option proto 'wireguard'
	option private_key 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
	option mtu '1280'
	list addresses 'someipv6/128'
	list addresses 'someipv4/32'
	list dns '127.0.0.1'
	list dns '::1' # you must have dhcpv6 package installed, if not remove this line or install it
	option ip6assign '128'

config wireguard_wg0
	option description 'Imported config'
	option public_key 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
	option endpoint_host 'engage.cloudflareclient.com'
	option endpoint_port '2408'
	option route_allowed_ips '1'
	list allowed_ips '::/0'
	list allowed_ips '0.0.0.0/0'

config route 'route_wireguard'
	option interface 'lan' # change to your interface name
	option target '0.0.0.0/0'
	option gateway '192.168.2.1'
	option metric '1024'

config route6
	option interface 'lan' # change to your interface name
	option target '::/0'
	option gateway 'fd47:e57f:d50d::1' # needs to change to your gateway ipv6
	option metric '1025'

```

and my /etc/config/dhcp file:
```python
config dhcp 'wan6'
	option interface 'wan6'
	option dhcpv6 'relay'
	option ra 'relay'
	option ndp 'relay'

config dhcp 'wg0'
	option interface 'wg0'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'
	option master '1'
```

Be sure to not copy paste my settings since there are a lot of things that are for my personal network and will not work for your one.

After those settings the https://ipv6-test.com/ returns:
![image](https://github.com/user-attachments/assets/eae6303c-b8b0-405e-ab1c-31281f63d752)

**Comment by spice42** [comment]
thanks for sharing

scroll down this page [https://www.ivpn.net/setup/router/openwrt-wireguard/](https://www.ivpn.net/setup/router/openwrt-wireguard/) and see how to create a killswitch, you might notice after a day or two, with the killswitch activated, the connection to wireguard drops in openwrt and does not come back up, its quite bad to not know you're not connected via wireguard, the only way you'll really know is to use a killswitch

since i learnt this, ive configured warp on every client i could rather than depend on openwrt, hope there is a solution via openwrt to reconnect wireguard on disconnection

**Comment by marcussacana** [comment]
Thanks for letting me know, I wasn't aware of this issue.
